In [1]:
import pandas as pd

In [2]:
ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
df = pd.DataFrame([[10, "a", True],
                  [20, "b", False],
                  [30, "c", False],
                  [40, "d", True]],)
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [ ]:
import numpy as np
df = pd.DataFrame(np.arange(100).reshape((25, 4)))

In [4]:
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [5]:
df.head()

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [6]:
df.tail()

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [7]:
df.shape

(4, 3)

In [10]:
df = pd.DataFrame([[10, "a", True],
                  [20, "b", False],
                  [30, "c", False],
                  [40, "d", True]],)
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [ ]:
df.index = ["01", "02", "03"]
df.columns = [""]

In [1]:
import pandas as pd
df = pd.read_csv("data/202411health.csv")

In [2]:
df = pd.read_excel("data/202411health.xlsx")
df

            日付     歩数  摂取カロリー
0   2024-11-01   5439    2500
1   2024-11-02   2510    2300
2   2024-11-03  10238    1950
3   2024-11-04   8209    1850
4   2024-11-05   9434    1930
5   2024-11-06   7593    1800
6   2024-11-07   9320    1940
7   2024-11-08   4873    2300
8   2024-11-09  12045    1950
9   2024-11-10   7493    1850
10  2024-11-11   7289    1930
11  2024-11-12   6481    2300
12  2024-11-13  10287    1800
13  2024-11-14   8043    1940
14  2024-11-15   7435    2300
15  2024-11-16   7529    2300
16  2024-11-17   8031    1940
17  2024-11-18   8475    2300
18  2024-11-19   8132    1950
19  2024-11-20  15328    1800
20  2024-11-21  12849    1940
21  2024-11-22   4029    2300
22  2024-11-23   3890    1950
23  2024-11-24   8093    1850
24  2024-11-25   7823    1950
25  2024-11-26   7492    1850
26  2024-11-27   7203    1930
27  2024-11-28   7302    1850
28  2024-11-29   6033    2300
29  2024-11-30   4093    1950

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("data/202411health.xlsx")
df

            日付     歩数  摂取カロリー
0   2024-11-01   5439    2500
1   2024-11-02   2510    2300
2   2024-11-03  10238    1950
3   2024-11-04   8209    1850
4   2024-11-05   9434    1930
5   2024-11-06   7593    1800
6   2024-11-07   9320    1940
7   2024-11-08   4873    2300
8   2024-11-09  12045    1950
9   2024-11-10   7493    1850
10  2024-11-11   7289    1930
11  2024-11-12   6481    2300
12  2024-11-13  10287    1800
13  2024-11-14   8043    1940
14  2024-11-15   7435    2300
15  2024-11-16   7529    2300
16  2024-11-17   8031    1940
17  2024-11-18   8475    2300
18  2024-11-19   8132    1950
19  2024-11-20  15328    1800
20  2024-11-21  12849    1940
21  2024-11-22   4029    2300
22  2024-11-23   3890    1950
23  2024-11-24   8093    1850
24  2024-11-25   7823    1950
25  2024-11-26   7492    1850
26  2024-11-27   7203    1930
27  2024-11-28   7302    1850
28  2024-11-29   6033    2300
29  2024-11-30   4093    1950

In [5]:
df.loc[:, "歩数"] >= 10000

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: 歩数, dtype: bool

In [6]:
df_selected = df.loc[df.loc[:, "歩数"] >= 10000, :]
df_selected

            日付     歩数  摂取カロリー
2   2024-11-03  10238    1950
8   2024-11-09  12045    1950
12  2024-11-13  10287    1800
19  2024-11-20  15328    1800
20  2024-11-21  12849    1940

In [7]:
df_selected.shape

(5, 3)

In [9]:
df.dtypes

日付          str
歩数        int64
摂取カロリー    int64
dtype: object

In [10]:
df["date"] = df.loc[:, "日付"].apply(pd.to_datetime)

In [11]:
df.loc[:, "date"]

0    2024-11-01
1    2024-11-02
2    2024-11-03
3    2024-11-04
4    2024-11-05
5    2024-11-06
6    2024-11-07
7    2024-11-08
8    2024-11-09
9    2024-11-10
10   2024-11-11
11   2024-11-12
12   2024-11-13
13   2024-11-14
14   2024-11-15
15   2024-11-16
16   2024-11-17
17   2024-11-18
18   2024-11-19
19   2024-11-20
20   2024-11-21
21   2024-11-22
22   2024-11-23
23   2024-11-24
24   2024-11-25
25   2024-11-26
26   2024-11-27
27   2024-11-28
28   2024-11-29
29   2024-11-30
Name: date, dtype: datetime64[us]

In [12]:
df

            日付     歩数  摂取カロリー       date
0   2024-11-01   5439    2500 2024-11-01
1   2024-11-02   2510    2300 2024-11-02
2   2024-11-03  10238    1950 2024-11-03
3   2024-11-04   8209    1850 2024-11-04
4   2024-11-05   9434    1930 2024-11-05
5   2024-11-06   7593    1800 2024-11-06
6   2024-11-07   9320    1940 2024-11-07
7   2024-11-08   4873    2300 2024-11-08
8   2024-11-09  12045    1950 2024-11-09
9   2024-11-10   7493    1850 2024-11-10
10  2024-11-11   7289    1930 2024-11-11
11  2024-11-12   6481    2300 2024-11-12
12  2024-11-13  10287    1800 2024-11-13
13  2024-11-14   8043    1940 2024-11-14
14  2024-11-15   7435    2300 2024-11-15
15  2024-11-16   7529    2300 2024-11-16
16  2024-11-17   8031    1940 2024-11-17
17  2024-11-18   8475    2300 2024-11-18
18  2024-11-19   8132    1950 2024-11-19
19  2024-11-20  15328    1800 2024-11-20
20  2024-11-21  12849    1940 2024-11-21
21  2024-11-22   4029    2300 2024-11-22
22  2024-11-23   3890    1950 2024-11-23
23  2024-11-24   8093    1850 2024-11-24
24  2024-11-25   7823    1950 2024-11-25
25  2024-11-26   7492    1850 2024-11-26
26  2024-11-27   7203    1930 2024-11-27
27  2024-11-28   7302    1850 2024-11-28
28  2024-11-29   6033    2300 2024-11-29
29  2024-11-30   4093    1950 2024-11-30

In [13]:
df["摂取カロリー"] = df.loc[:, "摂取カロリー"].astype(np.float32)

In [14]:
df = df.set_index("date")

In [15]:
df.head()

                    日付     歩数  摂取カロリー
date
2024-11-01  2024-11-01   5439  2500.0
2024-11-02  2024-11-02   2510  2300.0
2024-11-03  2024-11-03  10238  1950.0
2024-11-04  2024-11-04   8209  1850.0
2024-11-05  2024-11-05   9434  1930.0

In [16]:
df.sort_values(by="歩数")

                    日付     歩数  摂取カロリー
date
2024-11-02  2024-11-02   2510  2300.0
2024-11-23  2024-11-23   3890  1950.0
2024-11-22  2024-11-22   4029  2300.0
2024-11-30  2024-11-30   4093  1950.0
2024-11-08  2024-11-08   4873  2300.0
2024-11-01  2024-11-01   5439  2500.0
2024-11-29  2024-11-29   6033  2300.0
2024-11-12  2024-11-12   6481  2300.0
2024-11-27  2024-11-27   7203  1930.0
2024-11-11  2024-11-11   7289  1930.0
2024-11-28  2024-11-28   7302  1850.0
2024-11-15  2024-11-15   7435  2300.0
2024-11-26  2024-11-26   7492  1850.0
2024-11-10  2024-11-10   7493  1850.0
2024-11-16  2024-11-16   7529  2300.0
2024-11-06  2024-11-06   7593  1800.0
2024-11-25  2024-11-25   7823  1950.0
2024-11-17  2024-11-17   8031  1940.0
2024-11-14  2024-11-14   8043  1940.0
2024-11-24  2024-11-24   8093  1850.0
2024-11-19  2024-11-19   8132  1950.0
2024-11-04  2024-11-04   8209  1850.0
2024-11-18  2024-11-18   8475  2300.0
2024-11-07  2024-11-07   9320  1940.0
2024-11-05  2024-11-05   9434  1930.0
2024-11-03  2024-11-03  10238  1950.0
2024-11-13  2024-11-13  10287  1800.0
2024-11-09  2024-11-09  12045  1950.0
2024-11-21  2024-11-21  12849  1940.0
2024-11-20  2024-11-20  15328  1800.0

In [17]:
df.sort_values(by="歩数", ascending=False).head()

                    日付     歩数  摂取カロリー
date
2024-11-20  2024-11-20  15328  1800.0
2024-11-21  2024-11-21  12849  1940.0
2024-11-09  2024-11-09  12045  1950.0
2024-11-13  2024-11-13  10287  1800.0
2024-11-03  2024-11-03  10238  1950.0

In [18]:
df = df.drop("日付", axis=1)

In [19]:
df.tail()

              歩数  摂取カロリー
date
2024-11-26  7492  1850.0
2024-11-27  7203  1930.0
2024-11-28  7302  1850.0
2024-11-29  6033  2300.0
2024-11-30  4093  1950.0

In [20]:
df["歩数/カロリー"] = (df.loc[:, "歩数"]/
                      df.loc[:,"摂取カロリー"])
df

               歩数  摂取カロリー   歩数/カロリー
date
2024-11-01   5439  2500.0  2.175600
2024-11-02   2510  2300.0  1.091304
2024-11-03  10238  1950.0  5.250256
2024-11-04   8209  1850.0  4.437297
2024-11-05   9434  1930.0  4.888083
2024-11-06   7593  1800.0  4.218333
2024-11-07   9320  1940.0  4.804124
2024-11-08   4873  2300.0  2.118696
2024-11-09  12045  1950.0  6.176923
2024-11-10   7493  1850.0  4.050270
2024-11-11   7289  1930.0  3.776684
2024-11-12   6481  2300.0  2.817826
2024-11-13  10287  1800.0  5.715000
2024-11-14   8043  1940.0  4.145876
2024-11-15   7435  2300.0  3.232609
2024-11-16   7529  2300.0  3.273478
2024-11-17   8031  1940.0  4.139691
2024-11-18   8475  2300.0  3.684783
2024-11-19   8132  1950.0  4.170256
2024-11-20  15328  1800.0  8.515556
2024-11-21  12849  1940.0  6.623196
2024-11-22   4029  2300.0  1.751739
2024-11-23   3890  1950.0  1.994872
2024-11-24   8093  1850.0  4.374595
2024-11-25   7823  1950.0  4.011795
2024-11-26   7492  1850.0  4.049730
2024-11-27   7203  1930.0  3.732124
2024-11-28   7302  1850.0  3.947027
2024-11-29   6033  2300.0  2.623043
2024-11-30   4093  1950.0  2.098974

In [21]:
def exercise_judge(ex):
    if ex <= 3.0:
        return "Low"
    elif 3.0 < ex <= 6.0:
        return "Mid"
    else:
        return "High"

In [24]:
df["運動指数"] = df.loc[:, "歩数/カロリー"].apply(
    exercise_judge)
df

               歩数  摂取カロリー   歩数/カロリー  運動指数
date
2024-11-01   5439  2500.0  2.175600   Low
2024-11-02   2510  2300.0  1.091304   Low
2024-11-03  10238  1950.0  5.250256   Mid
2024-11-04   8209  1850.0  4.437297   Mid
2024-11-05   9434  1930.0  4.888083   Mid
2024-11-06   7593  1800.0  4.218333   Mid
2024-11-07   9320  1940.0  4.804124   Mid
2024-11-08   4873  2300.0  2.118696   Low
2024-11-09  12045  1950.0  6.176923  High
2024-11-10   7493  1850.0  4.050270   Mid
2024-11-11   7289  1930.0  3.776684   Mid
2024-11-12   6481  2300.0  2.817826   Low
2024-11-13  10287  1800.0  5.715000   Mid
2024-11-14   8043  1940.0  4.145876   Mid
2024-11-15   7435  2300.0  3.232609   Mid
2024-11-16   7529  2300.0  3.273478   Mid
2024-11-17   8031  1940.0  4.139691   Mid
2024-11-18   8475  2300.0  3.684783   Mid
2024-11-19   8132  1950.0  4.170256   Mid
2024-11-20  15328  1800.0  8.515556  High
2024-11-21  12849  1940.0  6.623196  High
2024-11-22   4029  2300.0  1.751739   Low
2024-11-23   3890  1950.0  1.994872   Low
2024-11-24   8093  1850.0  4.374595   Mid
2024-11-25   7823  1950.0  4.011795   Mid
2024-11-26   7492  1850.0  4.049730   Mid
2024-11-27   7203  1930.0  3.732124   Mid
2024-11-28   7302  1850.0  3.947027   Mid
2024-11-29   6033  2300.0  2.623043   Low
2024-11-30   4093  1950.0  2.098974   Low

In [25]:
df.to_pickle("data/df_202411health.pickle")

In [26]:
df_moved = pd.get_dummies(df.loc[:, "運動指数"],
    prefix="運動")
df_moved

            運動_High  運動_Low  運動_Mid
date
2024-11-01    False    True   False
2024-11-02    False    True   False
2024-11-03    False   False    True
2024-11-04    False   False    True
2024-11-05    False   False    True
2024-11-06    False   False    True
2024-11-07    False   False    True
2024-11-08    False    True   False
2024-11-09     True   False   False
2024-11-10    False   False    True
2024-11-11    False   False    True
2024-11-12    False    True   False
2024-11-13    False   False    True
2024-11-14    False   False    True
2024-11-15    False   False    True
2024-11-16    False   False    True
2024-11-17    False   False    True
2024-11-18    False   False    True
2024-11-19    False   False    True
2024-11-20     True   False   False
2024-11-21     True   False   False
2024-11-22    False    True   False
2024-11-23    False    True   False
2024-11-24    False   False    True
2024-11-25    False   False    True
2024-11-26    False   False    True
2024-11-27    False   False    True
2024-11-28    False   False    True
2024-11-29    False    True   False
2024-11-30    False    True   False

In [ ]:
df_moved.to