In [1]:
import pandas as pd

In [2]:
ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
df = pd.DataFrame([[10, "a", True],
                  [20, "b", False],
                  [30, "c", False],
                  [40, "d", True]],)
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [ ]:
import numpy as np
df = pd.DataFrame(np.arange(100).reshape((25, 4)))

In [4]:
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [5]:
df.head()

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [6]:
df.tail()

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [7]:
df.shape

(4, 3)

In [10]:
df = pd.DataFrame([[10, "a", True],
                  [20, "b", False],
                  [30, "c", False],
                  [40, "d", True]],)
df

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [ ]:
df.index = ["01", "02", "03"]
df.columns = [""]