In [2]:
import pandas as pd

In [5]:
df = pd.DataFrame([["A", 20, 80],
                  ["B", 22, 75],
                  ["C", 21, 90]])
df

   0   1   2
0  A  20  80
1  B  22  75
2  C  21  90

In [6]:
df.columns = ["Name", "Age", "Score"]
df

  Name  Age  Score
0    A   20     80
1    B   22     75
2    C   21     90

In [9]:
print(df.mean(numeric_only=True))

Age      21.000000
Score    81.666667
dtype: float64

In [13]:
df[df["Score"] >= 80]

  Name  Age  Score
0    A   20     80
2    C   21     90

In [1]:
import pandas as pd

In [2]:
data = {
    "id": [1,2,3,4,5,6],
    "name": ["A","B","C","D","E","F"],
    "age": [23,35,45,29,31,40],
    "score": [80,60,75,90,55,70]
}

df = pd.DataFrame(data)